### PR TITLE
Added Supply-Chain Attack

### PR DESCRIPTION
**Pull request by shannona**
One of the new adversaries (supply-chain attack) had some links to variant scenarios, so those updates are included here.

### CODE REVIEW

**Comment by ChristopherA** [comment]
I think our adversary counts may be off. In v1.0.0 see 10 in main list but it says "nine" above it, and in the optional list is 4 more, for a total of 14. Can you update your pull request to fix? Also, call this PR v1.0.1 since it is not substantive technically.

**Comment by shannona** [comment]
#s updated.

**Comment by ChristopherA** [comment]
Can you also update 1.0.1 date?

**Comment by shannona** [comment]
Done. Should be good to merge.

**Pull request merged**
